Repository PRIETAG/PRIETAG_FE, pull requests merged in 2023-07, with the labels that each got.

#89 색상 선택 설정, 업로드 모달 이슈 해결
  app/api/auth/[...nextauth]/route.ts
  app/editTemplate/components/ColorModal/ColorModalForm.tsx
  app/editTemplate/components/PriceModal/PriceModalForm.tsx
  app/editTemplate/components/UploadModal/Dropzone.tsx
  app/editTemplate/components/UploadModal/UploadModalForm.tsx
  app/editTemplate/page.tsx
  app/globals.css
  components/header/HomeHeader.tsx
  components/header/TemplateHeader.tsx
  store/slice/uploadModalSlice.tsx
  tailwind.config.js
Labels: 🔨 fix, ✨ feat, 💄 design

#94 priceCard와 관련된 타입 정리
  app/(auth)/editTemplate/components/PriceModal/PriceModalForm.tsx
  app/(auth)/editTemplate/components/RightMenu.tsx
  app/(auth)/editTemplate/components/Table/Table.tsx
  app/(auth)/editTemplate/page.tsx
  app/priceCard/components/PriceCardBox/PriceCard.tsx
  app/priceCard/components/PriceCardBox/PriceCardBox.tsx
  app/priceCard/components/PriceCardBox/PriceCardContent.tsx
  store/index.tsx
  store/slice/priceCardSlice.tsx
  store/slice/priceModalSlice.tsx
Labels: 🔨 fix, 🔥 remove, 💡 comment

#97 빌드 오류 수정
  app/(auth)/editTemplate/page.tsx
  app/(auth)/templateList/components/ViewDropDown.tsx
Labels: 🔨 fix
