Repository PRIETAG/PRIETAG_FE, pull requests merged in 2023-06, with the labels that each got.

#8 프로젝트 초기 세팅
  .eslintrc.json
  .gitignore
  .prettierrc
  README.md
  app/favicon.ico
  app/globals.css
  app/layout.tsx
  app/page.tsx
  next.config.js
  package-lock.json
  package.json
  postcss.config.js
  tailwind.config.js
  tsconfig.json
Labels: 🔨 fix, 🎉 init, ⚙️ conf, 🔥 remove, 🔧 add, 📦 chore

#13 PriceModal UI 구현
  .prettierrc
  .prettierrc.json
  app/editTemplate/components/PriceModal.tsx
  app/editTemplate/components/checkbox.tsx
  app/page.tsx
  lib/fonts.ts
  lib/utils.ts
  package-lock.json
  package.json
  tailwind.config.js
Labels: ✨ feat, ✏️ typo, 💄 design, 🔧 add, 📦 chore

#14 FAQ 컴포넌트 구현
  app/editTemplate/components/FAQ.tsx
  app/editTemplate/page.tsx
  package-lock.json
  package.json
Labels: ✨ feat, 📦 chore

#17 priceModal 배경 화면 및 정렬 설정
  app/editTemplate/components/PriceModal.tsx
  app/page.tsx
Labels: 💄 design

#18 Redux Slice 추가
  app/layout.tsx
  app/page.tsx
  components/Counter.tsx
  package.json
  store/index.tsx
  store/slice/counterslice.tsx
Labels: ✨ feat, ⚙️ conf, 🔧 add

#20 가격 카드 부분 컴포넌트 추가
  .eslintrc.json
  .github/COMMIT_TEMPLATE.txt
  .github/ISSUE_TEMPLATE.md
  app/helpers/StrictModeDroppable.tsx
  app/layout.tsx
  app/page.tsx
  app/priceCard/components/DiscountOptionBox/DiscountOptionBox.tsx
  app/priceCard/components/DiscountOptionBox/DiscountOptionSection/DiscountOptionSection.tsx
  app/priceCard/components/DiscountOptionBox/DiscountOptionSection/MonthYearChecked.tsx
  app/priceCard/components/DiscountOptionBox/DiscountOptionSection/UserCountChecked.tsx
  app/priceCard/components/DiscountOptionBox/PaddingBox.tsx
  app/priceCard/components/PriceCardBox/AddCardButton.tsx
  app/priceCard/components/PriceCardBox/PriceCard.tsx
  app/priceCard/components/PriceCardBox/PriceCardBox.tsx
  app/priceCard/page.tsx
  commitlint.config.js
  package-lock.json
  package.json
Labels: ✨ feat, 🔧 add, 📦 chore

#28 feat: modalSlice 및 GlobalModal 생성
  components/modal/ColorChangeModal.tsx
  components/modal/FAQModal.tsx
  components/modal/GlobalModal.tsx
  components/modal/Modal.tsx
  components/modal/ModalState.ts
  components/modal/PositionSelectModal.tsx
  components/modal/PriceChangeModal.tsx
  components/modal/PublishConfirmModal.tsx
  store/index.tsx
  store/slice/modalSlice.tsx
Labels: ✨ feat, 🗑️ style, 🔥 remove, 🔧 add

#29 가격표 설정 모달 기능 구현
  app/editTemplate/components/DropDown.tsx
  app/editTemplate/components/PriceModal.tsx
  app/editTemplate/page.tsx
  app/page.tsx
  components/dropdown-menu.tsx
  package-lock.json
  package.json
  store/index.tsx
  store/slice/priceModalSlice.tsx
Labels: ✨ feat, 🔥 remove, 💄 design, 🔧 add, 📦 chore

#34 Develop
  app/editTemplate/components/FAQ.tsx
  app/editTemplate/components/QnACard.tsx
  app/editTemplate/page.tsx
  store/index.tsx
  store/slice/faqSlice.tsx
Labels: ✨ feat, 🔧 add

#38 링크 모달, 헤더, 에러 페이지(반응형) 구현
  .vscode/settings.json
  app/dashboard/page.tsx
  app/editTemplate/page.tsx
  app/errorDelay/page.tsx
  app/errorNotGood/page.tsx
  app/layout.tsx
  components/Header.tsx
  components/header/Header.tsx
  components/header/HomeHeader.tsx
  components/header/TemplateHeader.tsx
  components/modal/ModalState.tsx
  components/modal/TempleteDeleteModal.tsx
  public/error_connection.svg
  public/error_slow.svg
  public/ezfee.svg
  store/ReduxProvider.tsx
  store/slice/modalSlice.tsx
Labels: ✨ feat, 🔥 remove, 💄 design, 🔧 add

#49 ColorModal 기능 구현
  app/editTemplate/components/ColorModal/ColorModal.tsx
  app/editTemplate/components/ColorModal/styles.css
  app/editTemplate/components/FAQ.tsx
  app/editTemplate/components/PriceModal.tsx
  app/editTemplate/components/RightMenu.tsx
  app/editTemplate/components/Slider.tsx
  app/editTemplate/page.tsx
  components/header/TemplateHeader.tsx
  package-lock.json
  package.json
  store/slice/colorModalSlicer.tsx
  store/slice/configSlice.tsx
  tailwind.config.js
  util/color.ts
Labels: ✨ feat, ✏️ typo, 🔥 remove, 💄 design, 🔧 add, 📦 chore

#50 FAQ 컴포넌트 구현
  app/editTemplate/components/FAQ.tsx
  app/editTemplate/components/QnACard.tsx
  app/editTemplate/components/RightMenu.tsx
  app/editTemplate/page.tsx
  store/slice/faqSlice.tsx
Labels: ✨ feat

#51 템플릿 리스트, 푸터 구현, public/img 파일 경로 수정
  app/dashboard/page.tsx
  app/editHistory/page.tsx
  app/editTemplate/page.tsx
  components/footer/Footer.tsx
  components/header/HomeHeader.tsx
  components/header/TemplateHeader.tsx
  components/modal/ModalState.tsx
  components/paginationBar/PaginationBar.tsx
  public/img/dropdown.svg
  public/img/error_connection.svg
  public/img/error_slow.svg
  public/img/ezfee.svg
  public/img/icon_account.svg
  public/img/page_first.svg
  public/img/page_pre.svg
  public/img/search.svg
  public/img/splash.svg
  public/img/upload_logo.svg
  store/slice/modalSlice.tsx
Labels: 💄 design, 🚚 rename

#53 UploadModal UI 구현
  app/editTemplate/components/UploadModal.tsx
  app/editTemplate/page.tsx
  app/page.tsx
  public/icons/icon_upload.svg
Labels: 🏭 refact, 💄 design

#55 로딩 페이지 구현
  app/Loading/page.tsx
  app/editTemplate/components/RightMenu.tsx
  public/loading.svg
Labels: 💄 design

#57 템플릿 페이지의 가격 카드 영역 가격, 할인율 변동
  app/editTemplate/components/PriceModal.tsx
  app/editTemplate/page.tsx
  app/priceCard/components/DiscountOptionBox/DiscountOptionBox.tsx
  app/priceCard/components/DiscountOptionBox/DiscountOptionSection/DiscountOptionSection.tsx
  app/priceCard/components/DiscountOptionBox/DiscountOptionSection/MonthYearChecked.tsx
  app/priceCard/components/DiscountOptionBox/DiscountOptionSection/UserCountChecked.tsx
  app/priceCard/components/PriceCardBox/PriceCard.tsx
  app/priceCard/components/PriceCardBox/PriceCardBox.tsx
  package-lock.json
  store/index.tsx
  store/slice/monthYearToggleSlice.tsx
  store/slice/priceCardSlice.tsx
  store/slice/priceModalSlice.tsx
Labels: 🔨 fix, ✨ feat, 🏭 refact, 💡 comment, 💄 design, 🔧 add

#61 💄 design: 반응형 디자인 수정
  app/errorDelay/page.tsx
  app/errorNotGood/page.tsx
  app/layout.tsx
  components/footer/Footer.tsx
  components/header/HomeHeader.tsx
  components/header/TemplateHeader.tsx
  package-lock.json
Labels: 💄 design

#63 가격 카드 오류 수정, 스타일 수정 및 정액제/정량제 로직 추가
  app/priceCard/components/DiscountOptionBox/DiscountOptionSection/DiscountOptionSection.tsx
  app/priceCard/components/DiscountOptionBox/DiscountOptionSection/MonthYearChecked.tsx
  app/priceCard/components/DiscountOptionBox/DiscountOptionSection/UserCountChecked.tsx
  app/priceCard/components/PriceCardBox/AddCardButton.tsx
  app/priceCard/components/PriceCardBox/PriceCard.tsx
  app/priceCard/components/PriceCardBox/PriceCardBox.tsx
  app/priceCard/components/PriceCardBox/PriceCardContent.tsx
  public/img/insert_card01.svg
  store/slice/priceModalSlice.tsx
Labels: 🔨 fix, ✨ feat, 💄 design

#65 미리보기 기능 구현
  app/editTemplate/components/DraggableArea/TextBox.tsx
  app/editTemplate/components/FAQ.tsx
  app/editTemplate/components/QnACard.tsx
  app/editTemplate/components/Table/Table.tsx
  app/editTemplate/components/Table/TableContainer.tsx
  app/editTemplate/page.tsx
  app/globals.css
  app/priceCard/components/PriceCardBox/AddCardButton.tsx
  app/priceCard/components/PriceCardBox/PriceCard.tsx
  app/priceCard/components/PriceCardBox/PriceCardBox.tsx
  app/priceCard/components/PriceCardBox/PriceCardContent.tsx
  components/header/TemplateHeader.tsx
  public/icons/desktop.svg
  public/icons/desktop_selected.svg
  public/icons/mobile.svg
  public/icons/mobile_selected.svg
  public/icons/tablet.svg
  public/icons/tablet_selected.svg
  store/slice/configSlice.tsx
  store/slice/priceModalSlice.tsx
  tailwind.config.js
Labels: ✨ feat, 💄 design

#66 로고 업로드 디스플레이 기능 구현
  app/editTemplate/components/PriceModal/PriceModalForm.tsx
  app/editTemplate/components/UploadModal/UploadModalForm.tsx
  app/editTemplate/page.tsx
  components/header/TemplateHeader.tsx
  store/slice/configSlice.tsx
Labels: ✨ feat, 🔥 remove, 💄 design

#67 편집 템플릿 탭 클릭시 초기 화면 UI 완성
  app/editHistory/components/TableList.tsx
  app/editHistory/page.tsx
  app/layout.tsx
  app/priceTable/page.tsx
  app/templateList/components/MoreDropDown.tsx
  app/templateList/components/PaginationBar.tsx
  app/templateList/components/ReturnToList.tsx
  app/templateList/components/SearchInput.tsx
  app/templateList/components/Subheader.tsx
  app/templateList/components/TableList.tsx
  app/templateList/components/TableTopRow.tsx
  app/templateList/components/ToggleDropDown.tsx
  app/templateList/components/ViewDropDown.tsx
  app/templateList/components/priceOptions.tsx
  app/templateList/edit/page.tsx
  app/templateList/page.tsx
  app/templateList/publish/page.tsx
  components/header/HomeHeader.tsx
  public/img/create.svg
  public/img/dropdown_s.svg
  public/img/dropup_s.svg
  public/img/edit.svg
  public/img/menu_dots.svg
Labels: 💄 design, 🚚 rename, 🔧 add

#69 가격 카드 영역 기능 추가/수정
  app/editTemplate/components/Table/Table.tsx
  app/priceCard/components/DiscountOptionBox/DiscountOptionBox.tsx
  app/priceCard/components/DiscountOptionBox/DiscountOptionSection/DiscountOptionSection.tsx
  app/priceCard/components/DiscountOptionBox/DiscountOptionSection/MonthYearChecked.tsx
  app/priceCard/components/DiscountOptionBox/DiscountOptionSection/UserCountChecked.tsx
  app/priceCard/components/PriceCardBox/AddCardButton.tsx
  app/priceCard/components/PriceCardBox/PriceCard.tsx
  app/priceCard/components/PriceCardBox/PriceCardBox.tsx
  app/priceCard/components/PriceCardBox/PriceCardContent.tsx
  store/slice/priceModalSlice.tsx
Labels: 🔨 fix, ✨ feat, 🏭 refact, 💄 design

#73 fix: 컴파일 에러 수정
  app/templateList/components/PaginationBar.tsx
  app/templateList/components/TableListExample.tsx
  app/templateList/edit/page.tsx
  store/slice/versionSlice.tsx
Labels: 🔨 fix

#74 :hammer: fix: build 오류 수정
  app/templateList/components/TableListExample.tsx
  app/templateList/edit/page.tsx
  components/modal/ModalState.tsx
  store/index.tsx
  store/slice/modalSlice.tsx
Labels: 🔨 fix

#77 css 깨짐 현상 해결
  app/globals.css
Labels: 🔨 fix

#79 로그인/로그아웃 기능 구현
  app/api/api.ts
  app/api/auth/[...nextauth]/route.ts
  components/header/HomeHeader.tsx
Labels: ✨ feat

#80 로그인 기능 개선
  app/api/auth/[...nextauth]/route.ts
  components/header/HomeHeader.tsx
Labels: ✨ feat

#81 💄홈 화면 수정
  app/page.tsx
  public/img/blueArrow.svg
  public/img/dashboard.png
  public/img/mediumCircle.svg
  public/img/price_table.png
  public/img/splash.png
  public/img/stroke.svg
Labels: 💄 design

#84 이벤트 객체 타입 지정
  .env
  app/templateList/components/MoreDropDown.tsx
  app/templateList/components/SearchInput.tsx
  app/templateList/components/ToggleDropDown.tsx
  app/templateList/page.tsx
Labels: 🏭 refact
